### ISSUE TITLE
category URLs not working

### ISSUE THREAD

**Issue by fipsingdale** [ovlb/reading#10]
Getting "Page Not Found" when reloading while on a category-page (like "https://reading.ovlb.net/c/architektur/") or when following a link to an article from it and then going back using browser navigation.

**Comment by ovlb** [comment]
Thanks. I guess it has something to do with Nuxt, generating dynamic routes and a section of the documentation I haven’t read properly. Will have a look into it.

**Comment by fipsingdale** [comment]
You're welcome. I think your nuxt.config.js is missing something like described here: https://nuxtjs.org/api/configuration-generate#function-which-returns-a-promise
